[deploy]
bucket = 'cfn-artifacts-20'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:244933296429:certificate/86c4649c-305a-4606-acf5-b7fa4453fc3c'
NetworkingStack = 'CrdNet'